steps:
  - name: gcr.io/proven-wavelet-314512/node
    entrypoint: yarn
    args: ["install"]
  - name: gcr.io/proven-wavelet-314512/node
    entrypoint: yarn
    args: ["run","build-sdk"]
  - name: gcr.io/proven-wavelet-314512/node
    entrypoint: npm
    args: ["artifactregistry-login", "./.npmrc"]
  - name: gcr.io/proven-wavelet-314512/node
    entrypoint: npm
    args: ["publish"]
