steps:
  - name: node
    entrypoint: yarn
    args: ["install"]
  - name: node
    entrypoint: yarn
    args: ["run", "build"]
  - name: node
    entrypoint: npm
    args: ["artifactregistry-login", "./.npmrc"]
  - name: node
    entrypoint: npm
    args: ["publish"]
